const formattedHorizonSchedule = [
    {
        "dateTime": "2018-09-01T17:00:00.000Z",
        "level": "USPHL 15 Pure/ Futures CT Rangers Labor Day",
        "home": "NJ Hitmen",
        "away": "Philadelphia",
        "location": "Chelsea Piers North",
        "fees": "6500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5891446",
        "status": "normal",
        "formattedLocation": "Chelsea Piers Connecticut",
        "locationAddress": "1 Blachley Rd, Stamford, CT 06902, United States"
    },
    {
        "dateTime": "2018-09-01T19:00:00.000Z",
        "level": "USPHL 15 Pure/ Futures CT Rangers Labor Day",
        "home": "Palm Beach Hawks",
        "away": "PAL Junior Islanders",
        "location": "Chelsea Piers North",
        "fees": "6500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5891447",
        "status": "normal",
        "formattedLocation": "Chelsea Piers Connecticut",
        "locationAddress": "1 Blachley Rd, Stamford, CT 06902, United States"
    },
    {
        "dateTime": "2018-09-01T21:00:00.000Z",
        "level": "USPHL 15 Pure/ Futures CT Rangers Labor Day",
        "home": "Cyclones",
        "away": "Islanders HC",
        "location": "Chelsea Piers North",
        "fees": "6500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5891448",
        "status": "normal",
        "formattedLocation": "Chelsea Piers Connecticut",
        "locationAddress": "1 Blachley Rd, Stamford, CT 06902, United States"
    },
    {
        "dateTime": "2018-09-01T23:30:00.000Z",
        "level": "USPHL 15 Pure/ Futures CT Rangers Labor Day",
        "home": "NJ Rockets",
        "away": "NJ Hitmen",
        "location": "Chelsea Piers South",
        "fees": "6500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5951613",
        "status": "normal",
        "formattedLocation": "Chelsea Piers Connecticut",
        "locationAddress": "1 Blachley Rd, Stamford, CT 06902, United States"
    },
    {
        "dateTime": "2018-09-02T21:00:00.000Z",
        "level": "USPHL 15 Pure/ Futures CT Rangers Labor Day",
        "home": "Philadelphia",
        "away": "Florida Blades",
        "location": "Chelsea Piers North",
        "fees": "6500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5891595",
        "status": "normal",
        "formattedLocation": "Chelsea Piers Connecticut",
        "locationAddress": "1 Blachley Rd, Stamford, CT 06902, United States"
    },
    {
        "dateTime": "2018-09-02T23:00:00.000Z",
        "level": "USPHL 15 Pure/ Futures CT Rangers Labor Day",
        "home": "NJ Rockets",
        "away": "Palm Beach Hawks",
        "location": "Chelsea Piers North",
        "fees": "6500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5891596",
        "status": "normal",
        "formattedLocation": "Chelsea Piers Connecticut",
        "locationAddress": "1 Blachley Rd, Stamford, CT 06902, United States"
    },
    {
        "dateTime": "2018-09-07T14:30:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Skate 3 Blue",
        "fees": "5500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5903093",
        "status": "normal",
        "formattedLocation": "Skate 3 Blue",
        "locationAddress": ""
    },
    {
        "dateTime": "2018-09-07T16:00:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Skate 3 Blue",
        "fees": "5500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5891341",
        "status": "normal",
        "formattedLocation": "Skate 3 Blue",
        "locationAddress": ""
    },
    {
        "dateTime": "2018-09-07T17:30:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Skate 3 Blue",
        "fees": "5500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5891342",
        "status": "normal",
        "formattedLocation": "Skate 3 Blue",
        "locationAddress": ""
    },
    {
        "dateTime": "2018-09-07T22:00:00.000Z",
        "level": "Super Series PeeWee",
        "home": "Super Series",
        "away": "PeeWee",
        "location": "Skate 3 Blue",
        "fees": "4500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5891348",
        "status": "normal",
        "formattedLocation": "Skate 3 Blue",
        "locationAddress": ""
    },
    {
        "dateTime": "2018-09-07T23:30:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Skate 3 Blue",
        "fees": "5500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5891349",
        "status": "normal",
        "formattedLocation": "Skate 3 Blue",
        "locationAddress": ""
    },
    {
        "dateTime": "2018-09-08T01:00:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Skate 3 Blue",
        "fees": "5500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5891350",
        "status": "normal",
        "formattedLocation": "Skate 3 Blue",
        "locationAddress": ""
    },
    {
        "dateTime": "2018-09-08T12:00:00.000Z",
        "level": "Super Series PeeWee",
        "home": "Super Series",
        "away": "PeeWee",
        "location": "Salem NH - Olympic",
        "fees": "4500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5894367",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2018-09-08T13:30:00.000Z",
        "level": "Super Series PeeWee",
        "home": "Super Series",
        "away": "PeeWee",
        "location": "Salem NH - Olympic",
        "fees": "4500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5894365",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2018-09-08T15:00:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Salem NH - Olympic",
        "fees": "5500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5894366",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2018-09-08T21:10:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Salem NH - NHL",
        "fees": "5500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5894362",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2018-09-08T22:40:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Salem NH - NHL",
        "fees": "5500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5894363",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2018-09-09T00:10:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Salem NH - NHL",
        "fees": "5500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5894361",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2018-09-29T21:10:00.000Z",
        "level": "USPHL U16",
        "home": "CT  Jr. Rangers",
        "away": "Philadelphia",
        "location": "Stamford Twin Rink",
        "fees": "9000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5959622",
        "status": "normal",
        "formattedLocation": "Stamford Twin Rinks",
        "locationAddress": "1063 Hope St, Stamford, CT 06907, United States"
    },
    {
        "dateTime": "2018-09-29T23:30:00.000Z",
        "level": "USPHL U16",
        "home": "CT  Jr. Rangers",
        "away": "Cyclones",
        "location": "Stamford Twin Rink",
        "fees": "6500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "6022180",
        "status": "normal",
        "formattedLocation": "Stamford Twin Rinks",
        "locationAddress": "1063 Hope St, Stamford, CT 06907, United States"
    },
    {
        "dateTime": "2018-09-30T13:40:00.000Z",
        "level": "USPHL U16",
        "home": "CT Jr. Rangers #2",
        "away": "Philadelphia",
        "location": "Stamford Twin Rink",
        "fees": "6500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5959633",
        "status": "normal",
        "formattedLocation": "Stamford Twin Rinks",
        "locationAddress": "1063 Hope St, Stamford, CT 06907, United States"
    },
    {
        "dateTime": "2018-09-30T16:50:00.000Z",
        "level": "USPHL U16",
        "home": "CT  Jr. Rangers",
        "away": "Cyclones",
        "location": "Stamford Twin Rink",
        "fees": "9000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5996699",
        "status": "normal",
        "formattedLocation": "Stamford Twin Rinks",
        "locationAddress": "1063 Hope St, Stamford, CT 06907, United States"
    },
    {
        "dateTime": "2018-10-08T17:00:00.000Z",
        "level": "Hitmen Showcase U16",
        "home": "Pics",
        "away": "Philadelphia",
        "location": "Ice Vault 3",
        "fees": 0,
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "6051203",
        "status": "canceled",
        "formattedLocation": "Ice Vault 3",
        "locationAddress": ""
    },
    {
        "dateTime": "2018-10-08T19:00:00.000Z",
        "level": "Hitmen Showcase U16",
        "home": "NJ Rockets",
        "away": "SSKings",
        "location": "Ice Vault 3",
        "fees": "6500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "6051205",
        "status": "normal",
        "formattedLocation": "Ice Vault 3",
        "locationAddress": ""
    },
    {
        "dateTime": "2018-10-08T20:50:00.000Z",
        "level": "Hitmen Showcase U16",
        "home": "NH Jr Monarchs",
        "away": "Skipjacks",
        "location": "Ice Vault 3",
        "fees": "9000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "6051208",
        "status": "normal",
        "formattedLocation": "Ice Vault 3",
        "locationAddress": ""
    },
    {
        "dateTime": "2018-10-13T23:00:00.000Z",
        "level": "EHL",
        "home": "NY Applecore",
        "away": "New Jersey 87's",
        "location": "Brewster Arena 98",
        "fees": "7500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5867945",
        "status": "normal",
        "formattedLocation": "Brewster Ice Arena",
        "locationAddress": "63 Fields Ln, Brewster, NY 10509, United States"
    },
    {
        "dateTime": "2018-10-14T21:30:00.000Z",
        "level": "USPHL U18",
        "home": "CT  Jr. Rangers",
        "away": "Jersey Shore Whalers",
        "location": "Chelsea Piers South",
        "fees": 0,
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5978060",
        "status": "canceled",
        "formattedLocation": "Chelsea Piers Connecticut",
        "locationAddress": "1 Blachley Rd, Stamford, CT 06902, United States"
    },
    {
        "dateTime": "2018-10-14T21:30:00.000Z",
        "level": "USPHL U16",
        "home": "CT  Jr. Rangers",
        "away": "NJ Hitmen",
        "location": "Chelsea Piers North",
        "fees": 0,
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5985764",
        "status": "canceled",
        "formattedLocation": "Chelsea Piers Connecticut",
        "locationAddress": "1 Blachley Rd, Stamford, CT 06902, United States"
    },
    {
        "dateTime": "2018-12-01T23:45:00.000Z",
        "level": "USPHL U16",
        "home": "CT  Jr. Rangers",
        "away": "CT Nighthawks",
        "location": "Stamford Twin Rink",
        "fees": 0,
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "5996722",
        "status": "canceled",
        "formattedLocation": "Stamford Twin Rinks",
        "locationAddress": "1063 Hope St, Stamford, CT 06907, United States"
    },
    {
        "dateTime": "2018-12-15T23:00:00.000Z",
        "level": "South Kent N/L Midget",
        "home": "Selects Academy",
        "away": "Midgets U16",
        "location": "South Kent Stockdale Arena",
        "fees": "9000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "6511801",
        "status": "normal",
        "formattedLocation": "Admiral Stockdale Arena",
        "locationAddress": "South Kent, CT 06785, United States"
    },
    {
        "dateTime": "2018-12-16T01:00:00.000Z",
        "level": "South Kent N/L Midget",
        "home": "Selects Academy",
        "away": "Midgets U18",
        "location": "South Kent Stockdale Arena",
        "fees": "9000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "6511802",
        "status": "normal",
        "formattedLocation": "Admiral Stockdale Arena",
        "locationAddress": "South Kent, CT 06785, United States"
    },
    {
        "dateTime": "2019-01-18T05:00:00.000Z",
        "level": "South Kent N/L Midget",
        "home": "Selects Academy",
        "away": "Midgets U15",
        "location": "South Kent Stockdale Arena",
        "fees": 0,
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "6444502",
        "status": "canceled",
        "formattedLocation": "Admiral Stockdale Arena",
        "locationAddress": "South Kent, CT 06785, United States"
    },
    {
        "dateTime": "2019-01-18T05:00:00.000Z",
        "level": "South Kent N/L Midget",
        "home": "Selects Academy",
        "away": "Midgets U15",
        "location": "South Kent Stockdale Arena",
        "fees": 0,
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "6444503",
        "status": "canceled",
        "formattedLocation": "Admiral Stockdale Arena",
        "locationAddress": "South Kent, CT 06785, United States"
    },
    {
        "dateTime": "2019-02-17T15:00:00.000Z",
        "level": "South Kent N/L Midget",
        "home": "Selects Academy",
        "away": "Midgets U18",
        "location": "South Kent Stockdale Arena",
        "fees": "9000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "6444538",
        "status": "normal",
        "formattedLocation": "Admiral Stockdale Arena",
        "locationAddress": "South Kent, CT 06785, United States"
    },
    {
        "dateTime": "2019-08-30T16:00:00.000Z",
        "level": "Labor Day Face Off U18",
        "home": "Labor Day Face-Off",
        "away": "Midgets U18",
        "location": "Foxboro 1",
        "fees": "7000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7917460",
        "status": "normal",
        "formattedLocation": "Foxboro Sports Center",
        "locationAddress": "10 E Belcher Rd, Foxborough, MA 02035, United States"
    },
    {
        "dateTime": "2019-08-30T17:40:00.000Z",
        "level": "Labor Day Face Off U18",
        "home": "Labor Day Face-Off",
        "away": "Midgets U18",
        "location": "Foxboro 1",
        "fees": "7000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7917459",
        "status": "normal",
        "formattedLocation": "Foxboro Sports Center",
        "locationAddress": "10 E Belcher Rd, Foxborough, MA 02035, United States"
    },
    {
        "dateTime": "2019-08-30T23:00:00.000Z",
        "level": "Labor Day Face Off U16",
        "home": "Labor Day Face-Off",
        "away": "Midgets U16",
        "location": "Foxboro 3",
        "fees": "7000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7917506",
        "status": "normal",
        "formattedLocation": "Foxboro Sports Center",
        "locationAddress": "10 E Belcher Rd, Foxborough, MA 02035, United States"
    },
    {
        "dateTime": "2019-08-31T00:40:00.000Z",
        "level": "Labor Day Face Off U18",
        "home": "Labor Day Face-Off",
        "away": "Midgets U18",
        "location": "Foxboro 3",
        "fees": "7000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7917507",
        "status": "normal",
        "formattedLocation": "Foxboro Sports Center",
        "locationAddress": "10 E Belcher Rd, Foxborough, MA 02035, United States"
    },
    {
        "dateTime": "2019-08-31T11:50:00.000Z",
        "level": "Labor Day Face Off U16",
        "home": "Labor Day Face-Off",
        "away": "Midgets U16",
        "location": "Foxboro 3",
        "fees": "7000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7917558",
        "status": "normal",
        "formattedLocation": "Foxboro Sports Center",
        "locationAddress": "10 E Belcher Rd, Foxborough, MA 02035, United States"
    },
    {
        "dateTime": "2019-08-31T13:30:00.000Z",
        "level": "Labor Day Face Off U18",
        "home": "Labor Day Face-Off",
        "away": "Midgets U18",
        "location": "Foxboro 3",
        "fees": "7000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7917559",
        "status": "normal",
        "formattedLocation": "Foxboro Sports Center",
        "locationAddress": "10 E Belcher Rd, Foxborough, MA 02035, United States"
    },
    {
        "dateTime": "2019-08-31T18:40:00.000Z",
        "level": "Labor Day Face Off U18",
        "home": "Labor Day Face-Off",
        "away": "Midgets U18",
        "location": "Foxboro 2",
        "fees": "7000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7917556",
        "status": "normal",
        "formattedLocation": "Foxboro Sports Center",
        "locationAddress": "10 E Belcher Rd, Foxborough, MA 02035, United States"
    },
    {
        "dateTime": "2019-08-31T20:20:00.000Z",
        "level": "Labor Day Face Off U18",
        "home": "Labor Day Face-Off",
        "away": "Midgets U18",
        "location": "Foxboro 2",
        "fees": "7000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7917557",
        "status": "normal",
        "formattedLocation": "Foxboro Sports Center",
        "locationAddress": "10 E Belcher Rd, Foxborough, MA 02035, United States"
    },
    {
        "dateTime": "2019-09-06T16:40:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Salem NH - NHL",
        "fees": "5500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7929038",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2019-09-06T18:10:00.000Z",
        "level": "Super Series PeeWee",
        "home": "Super Series",
        "away": "PeeWee",
        "location": "Salem NH - NHL",
        "fees": "4500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7929039",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2019-09-07T12:00:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Salem NH - Olympic",
        "fees": "5500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7919707",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2019-09-07T13:30:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Salem NH - Olympic",
        "fees": "5500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7919708",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2019-09-07T15:00:00.000Z",
        "level": "Super Series PeeWee",
        "home": "Super Series",
        "away": "PeeWee",
        "location": "Salem NH - Olympic",
        "fees": "4500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7919709",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2019-09-07T21:10:00.000Z",
        "level": "Super Series PeeWee",
        "home": "Super Series",
        "away": "PeeWee",
        "location": "Salem NH - NHL",
        "fees": "4500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7919730",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2019-09-07T22:40:00.000Z",
        "level": "Super Series PeeWee",
        "home": "Super Series",
        "away": "PeeWee",
        "location": "Salem NH - NHL",
        "fees": "4500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7919731",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2019-09-08T00:10:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Salem NH - NHL",
        "fees": 0,
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7919732",
        "status": "canceled",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2019-09-08T11:00:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Salem NH - Olympic",
        "fees": "5500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7931856",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2019-09-08T12:30:00.000Z",
        "level": "Super Series Bantam",
        "home": "Super Series",
        "away": "Bantam",
        "location": "Salem NH - Olympic",
        "fees": "5500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7931857",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2019-09-08T14:00:00.000Z",
        "level": "Super Series PeeWee",
        "home": "Super Series",
        "away": "PeeWee",
        "location": "Salem NH - Olympic",
        "fees": "4500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "7931858",
        "status": "normal",
        "formattedLocation": "Icenter Salem",
        "locationAddress": "60 Lowell Rd, Salem, NH 03079, United States"
    },
    {
        "dateTime": "2019-09-28T18:50:00.000Z",
        "level": "Yale Midget TRNY",
        "home": "Yale Jamboree",
        "away": "Midget",
        "location": "East Haven Veterans Memorial Arena",
        "fees": "8500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "8038251",
        "status": "normal",
        "formattedLocation": "East Haven Veterans Memorial Ice Rink",
        "locationAddress": "71 Hudson St, East Haven, CT 06512, United States"
    },
    {
        "dateTime": "2019-09-28T20:20:00.000Z",
        "level": "Yale Midget TRNY",
        "home": "Yale Jamboree",
        "away": "Midget",
        "location": "East Haven Veterans Memorial Arena",
        "fees": "8500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "8038252",
        "status": "normal",
        "formattedLocation": "East Haven Veterans Memorial Ice Rink",
        "locationAddress": "71 Hudson St, East Haven, CT 06512, United States"
    },
    {
        "dateTime": "2019-09-28T21:50:00.000Z",
        "level": "Yale Midget TRNY",
        "home": "Yale Jamboree",
        "away": "Midget",
        "location": "East Haven Veterans Memorial Arena",
        "fees": "8500",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "8038253",
        "status": "normal",
        "formattedLocation": "East Haven Veterans Memorial Ice Rink",
        "locationAddress": "71 Hudson St, East Haven, CT 06512, United States"
    },
    {
        "dateTime": "2019-10-05T14:35:00.000Z",
        "level": "PA Elites Midgets",
        "home": "PA Elite Hockey",
        "away": "Midgets U18",
        "location": "Northford Ice Pavilion- Blue",
        "fees": "8000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "8143332",
        "status": "normal",
        "formattedLocation": "Northford Ice Pavilion",
        "locationAddress": "24 Fire-Lite Pl, Northford, CT 06472, United States"
    },
    {
        "dateTime": "2019-10-05T16:10:00.000Z",
        "level": "PA Elites Midgets",
        "home": "PA Elite Hockey",
        "away": "Midgets U16",
        "location": "Northford Ice Pavilion- Blue",
        "fees": "8000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "8143333",
        "status": "normal",
        "formattedLocation": "Northford Ice Pavilion",
        "locationAddress": "24 Fire-Lite Pl, Northford, CT 06472, United States"
    },
    {
        "dateTime": "2019-10-05T16:15:00.000Z",
        "level": "PA Elites Midgets",
        "home": "PA Elite Hockey",
        "away": "Midgets U16",
        "location": "Northford Ice Pavilion- Blue",
        "fees": 0,
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "8143334",
        "status": "canceled",
        "formattedLocation": "Northford Ice Pavilion",
        "locationAddress": "24 Fire-Lite Pl, Northford, CT 06472, United States"
    },
    {
        "dateTime": "2019-10-05T20:05:00.000Z",
        "level": "PA Elites Midgets",
        "home": "PA Elite Hockey",
        "away": "Midgets U15",
        "location": "Northford Ice Pavilion- White",
        "fees": "8000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "8143388",
        "status": "normal",
        "formattedLocation": "Northford Ice Pavilion",
        "locationAddress": "24 Fire-Lite Pl, Northford, CT 06472, United States"
    },
    {
        "dateTime": "2019-10-05T21:40:00.000Z",
        "level": "PA Elites Midgets",
        "home": "PA Elite Hockey",
        "away": "Midgets U16",
        "location": "Northford Ice Pavilion- White",
        "fees": "8000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "8143364",
        "status": "normal",
        "formattedLocation": "Northford Ice Pavilion",
        "locationAddress": "24 Fire-Lite Pl, Northford, CT 06472, United States"
    },
    {
        "dateTime": "2019-10-05T23:15:00.000Z",
        "level": "PA Elites Midgets",
        "home": "PA Elite Hockey",
        "away": "Midgets U18",
        "location": "Northford Ice Pavilion- White",
        "fees": "8000",
        "group": "Referees Crease Youth",
        "position": "Referee",
        "paid": true,
        "gameId": "8143365",
        "status": "normal",
        "formattedLocation": "Northford Ice Pavilion",
        "locationAddress": "24 Fire-Lite Pl, Northford, CT 06472, United States"
    }
]
module.exports = formattedHorizonSchedule